"""create repositories table

Revision ID: 90306ed15611
Revises: 61c6f5d586a9
Create Date: 2026-07-17 02:34:20.757210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90306ed15611'
down_revision = '61c6f5d586a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repositories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('repo_url', sa.String(length=500), nullable=False),
    sa.Column('branch', sa.String(length=100), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('repositories')
    # ### end Alembic commands ###
